### ISSUE TITLE
Remove the /files/ of path.

### ISSUE THREAD

**Issue by YacheLee** [mayth/go-simple-upload-server#3]
Maybe use /files/ as prefix for path is too much.
Could you please remove /files/ prefix of path by default?

**Comment by mayth** [comment]
Sorry for my late reply.

As you know, `/files` is an "endpoint" for accessing to a file, not a prefix.
I can provide all current features with putting all endpoints into `/` (e.g. `POST /upload` -> `POST /`, `PUT /files/:filename` -> `PUT /:filename`). However, I do not so. It is because I think they won't be "self-contained" URIs.
This is my policy of API design.
I understand your suggestion, but I will not change the current API.

In addition, since this server is not a framework (but just a dedicated application server), API endpoints are not configurable. There is no plan to make it configurable.
