### ISSUE TITLE
MaxFileSize not working

### ISSUE THREAD

**Issue by NicoSchirmeier** [mayth/go-simple-upload-server#32]
I am running the server in a kubernetes statefulset. 
Generally the upload is working. The problem is that the MaximumFileSize I set doesn´t seem to have any affect.
I also understand that this error should be Logged which it isn´t.

`time="2021-04-08T07:26:13Z" level=info msg="starting up simple-upload-server"
time="2021-04-08T07:26:13Z" level=info msg="start listening" cors=false ip=0.0.0.0 port=25478 root=/var/root token=<yes> upload_limit=72118430`

The server returns this:
(413) Request Entity Too Large.

the file size is around 7500Kb so the upload size I set should be plenty enough. I have tried several diffrent upload sizes.
I don´t know much about go but as my upload size is logged correctly I figure it probably parses correctly as well.

Btw. it would be great to have support for docker exec :)

**Comment by mayth** [comment]
Sorry for late reply, and thank you for your reporting :)

As the log shows, MaxUploadSize (`-upload_limit`) seems to be set correctly.
> ```
> time="2021-04-08T07:26:13Z" level=info msg="start listening" cors=false ip=0.0.0.0 port=25478 root=/var/root token=<yes> upload_limit=72118430
> ```

The request is logged with message "file size exceeded" when this app rejects the request due to the size limit.

If you can't find that message, the request is not reached to this app.
You wrote that you are trying to run this app on k8s, so there might be Ingress controller like ingress-nginx. It has the limit for the uploaded body size which is independent of this app's limit. You may have to modify its configuration.

**Comment by NicoSchirmeier** [comment]
Yes, thanks fro the reply. It was the Ingress
